# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk13.0.1

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту youremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - markdrrr@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
        - CODECOV_TOKEN="2da11565-002b-4f86-a3a0-8e94e247e164"